### ISSUE TITLE
Creation du dossier ognons fresh install

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/Ognon#42]
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/ognon/server.py", line 58, in call_function
    return f(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/ognon/view.py", line 22, in get
    reply[view_function] = fun(cursor, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/ognon/view.py", line 51, in get_projects
    return [proj for proj in projects.get_saved_projects_list()]
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/ognon/projects.py", line 27, in get_saved_projects_list
    return list(filter(ignore_files, os.listdir(PROJECTS_DIR)))
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/ognons/'
17:55:17:018 WARNING: Oups...
```

**Comment by LeonLenclos** [comment]
```
Traceback (most recent call last):
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/server.py", line 59, in call_function
    return f(*args, **kwargs)
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/control/__init__.py", line 14, in wrapped
    return fun(cursor, *args, **kwargs)
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/control/projectmanager.py", line 13, in load
    cursor.proj = projects.load(name)
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/projects.py", line 57, in load
    return load_from_path(PROJECTS_DIR + name)
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/projects.py", line 38, in load_from_path
    for file in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/leon/ognons/new_project'
14:37:56:158 WARNING: Oups...
Traceback (most recent call last):
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/server.py", line 59, in call_function
    return f(*args, **kwargs)
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/control/__init__.py", line 14, in wrapped
    return fun(cursor, *args, **kwargs)
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/control/projectmanager.py", line 13, in load
    cursor.proj = projects.load(name)
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/projects.py", line 57, in load
    return load_from_path(PROJECTS_DIR + name)
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/projects.py", line 38, in load_from_path
    for file in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/leon/ognons/new_project'
14:37:57:354 WARNING: Oups...
Traceback (most recent call last):
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/server.py", line 59, in call_function
    return f(*args, **kwargs)
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/view.py", line 42, in get_projects
    return sorted([proj for proj in projects.get_saved_projects_list()])
  File "/home/leon/.virtualenvs/ogn/lib/python3.9/site-packages/ognon/projects.py", line 27, in get_saved_projects_list
    return list(filter(ignore_files, os.listdir(PROJECTS_DIR)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/leon/ognons/'

```
